GET http://localhost:8080/metrics?after=2020-02-01T20:47:14.511Z&chronounit=HOURS
Accept: application/json

###
GET http://localhost:8080/metrics?after=2020-02-01T20:47:14.511Z&chronounit=DAYS
Accept: application/json

###
