
spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  jpa:
    database: "H2"
    hibernate:
      ddl-auto: "create"
logging:
  level:
    org.springframework.jdbc: "INFO"
    org.springframework.web: "INFO"